/**
 * Utilities for reading, sanitizing, and staging a `sonar-project.properties`
 * file for sonar-scanner invocations.
 *
 * SonarQube's community convention is that project-level configuration
 * (`sonar.projectKey`, `sonar.sources`, `sonar.exclusions`, etc.) lives in a
 * file at the project root. This CLI reads that file as the source of truth
 * for project analysis configuration — the CLI only controls the orchestration
 * layer (server URL, token, scan mode).
 *
 * In managed mode the CLI provisions an ephemeral SonarQube container and
 * must force `sonar.host.url` + `sonar.token` regardless of what the
 * user's file says. Those overrides also pass through the sanitizer.
 *
 * To avoid mutating the user's repo, the sanitized copy is written to a
 * non-cwd temp directory (for local sonar-scanner) or to a unique hidden file
 * inside cwd (for the container runner, which mounts cwd). A cleanup function
 * is returned and MUST be called in a finally block.
 */

import { readFile, writeFile, unlink, mkdtemp, rm } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { tmpdir } from 'node:os';
import { logger } from '@infra/utils/logger';
import { CLI_NAME, DEFAULT_SONAR_DOTFILE, DEFAULT_SONAR_TEMPDIR_PREFIX } from '@infra/brand';

/**
 * Keys the CLI owns — values in the user's file are ignored and the CLI
 * always wins via `-D` args (which have higher precedence than properties
 * file entries). Listed so we can strip them from the sanitized copy too —
 * keeps the file clean and avoids confusion if someone `cat`s it.
 */
export const CLI_OWNED_KEYS = ['sonar.host.url', 'sonar.token'] as const;

const SONAR_PROPERTIES_FILENAME = 'sonar-project.properties';

/**
 * Parse a `.properties`-style file into a Map<key, value>.
 *
 * Simple line-oriented parser:
 * - Lines starting with `#` or `!` are comments (skipped).
 * - Blank lines are skipped.
 * - `key=value` and `key:value` are both accepted (per Java Properties spec).
 * - Whitespace around `=`/`:` is trimmed.
 * - Backslash-continuation lines are NOT supported (rare in sonar files; would
 *   add complexity for little value here).
 * - Later occurrences of the same key overwrite earlier ones (last-wins).
 *
 * Returns an empty Map if the input has no valid entries.
 */
export function parsePropertiesFile(content: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#') || line.startsWith('!')) continue;

    // Find first '=' or ':' as the separator (whichever appears first)
    const eqIdx = line.indexOf('=');
    const colIdx = line.indexOf(':');
    const sepIdx =
      eqIdx === -1 ? colIdx :
      colIdx === -1 ? eqIdx :
      Math.min(eqIdx, colIdx);

    if (sepIdx <= 0) continue; // no separator or key is empty

    const key = line.slice(0, sepIdx).trim();
    const value = line.slice(sepIdx + 1).trim();
    if (!key) continue;

    out.set(key, value);
  }
  return out;
}

/**
 * Read the project's `sonar-project.properties` (if present).
 *
 * Returns null when the file does not exist (caller decides whether that's
 * an error — scanner will usually need it).
 */
export async function readSonarProperties(cwd: string): Promise<Map<string, string> | null> {
  try {
    const content = await readFile(resolve(cwd, SONAR_PROPERTIES_FILENAME), 'utf-8');
    return parsePropertiesFile(content);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw err;
  }
}

/**
 * Serialize a properties Map back to a `.properties` file string.
 *
 * Keys are emitted in insertion order. Values are written verbatim (no
 * escaping) — this matches how sonar-scanner reads them back.
 */
export function serializePropertiesFile(props: Map<string, string>): string {
  const lines: string[] = [
    `# Generated by ${CLI_NAME} (sanitized copy of sonar-project.properties).`,
    '# The original user file is untouched; this copy exists only for this scanner invocation.',
    '',
  ];
  for (const [key, value] of props) {
    lines.push(`${key}=${value}`);
  }
  return lines.join('\n') + '\n';
}

/** Location strategy for the sanitized temp file. */
export type SanitizedFileLocation = 'os-tmpdir' | 'cwd-hidden';

export interface SanitizeOptions {
  cwd: string;
  /**
   * Where to place the sanitized file:
   * - 'os-tmpdir' (default): `os.tmpdir()/<CLI_NAME>-sonar-XXXX/sonar-project.properties`
   *   — safest, but the container runner can't read it without extra mounts.
   * - 'cwd-hidden': `<cwd>/${DEFAULT_SONAR_DOTFILE}` (dotfile prefix
   *   keeps it off most listings; cleanup always runs in finally). Use when
   *   sonar-scanner runs inside a container that only mounts cwd.
   */
  location?: SanitizedFileLocation;
  /**
   * Keys whose values should OVERRIDE whatever is in the user's file.
   * Applied after stripping. Example: `{ 'sonar.projectKey': 'resolved-key' }`.
   */
  overrides?: Record<string, string>;
  /**
   * Keys to strip in addition to CLI_OWNED_KEYS.
   */
  extraStripKeys?: readonly string[];
}

export interface SanitizedPropertiesFile {
  /** Absolute path to the sanitized file. Pass to sonar-scanner via `-Dproject.settings=<path>`. */
  path: string;
  /** Call in a finally block. Idempotent — safe to invoke multiple times. */
  cleanup: () => Promise<void>;
  /** List of keys that were stripped (for logging / UX). */
  strippedKeys: string[];
  /** True when the user did not have a sonar-project.properties; a minimal one was synthesized. */
  fromScratch: boolean;
}

/**
 * Read the user's `sonar-project.properties`, strip CLI-owned keys, apply
 * overrides, write the result to a temp path, return the path +
 * cleanup function.
 *
 * When no user file exists, synthesizes one from the overrides alone — this
 * is a corner case (misconfigured project), recorded via `fromScratch: true`
 * so the engine can emit a pointed error if needed.
 */
export async function sanitizeAndWriteProperties(
  opts: SanitizeOptions,
): Promise<SanitizedPropertiesFile> {
  const { cwd, location = 'os-tmpdir', overrides = {}, extraStripKeys = [] } = opts;

  const userProps = (await readSonarProperties(cwd)) ?? new Map<string, string>();
  const fromScratch = userProps.size === 0;

  // Union of all keys we always strip.
  const stripSet = new Set<string>([
    ...CLI_OWNED_KEYS,
    ...extraStripKeys,
  ]);

  const strippedKeys: string[] = [];
  const sanitized = new Map<string, string>();
  for (const [key, value] of userProps) {
    if (stripSet.has(key)) {
      strippedKeys.push(key);
      continue;
    }
    sanitized.set(key, value);
  }

  // Apply overrides (CLI-controlled values always win).
  for (const [key, value] of Object.entries(overrides)) {
    sanitized.set(key, value);
  }

  const { filePath, cleanup } = await writeSanitizedFile(cwd, location, sanitized);

  return { path: filePath, cleanup, strippedKeys, fromScratch };
}

/** Write the sanitized properties to the chosen location and return a cleanup. */
async function writeSanitizedFile(
  cwd: string,
  location: SanitizedFileLocation,
  props: Map<string, string>,
): Promise<{ filePath: string; cleanup: () => Promise<void> }> {
  const content = serializePropertiesFile(props);

  if (location === 'cwd-hidden') {
    const filePath = resolve(cwd, DEFAULT_SONAR_DOTFILE);
    await writeFile(filePath, content, 'utf-8');
    const cleanup = async (): Promise<void> => {
      try {
        await unlink(filePath);
      } catch (err) {
        // ENOENT on cleanup is fine (already removed by another path)
        if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
          logger.warn(`[SonarQube] failed to remove sanitized properties at ${filePath}: ${String(err)}`);
        }
      }
    };
    return { filePath, cleanup };
  }

  // os-tmpdir: isolate in a dedicated temp directory so we can rm -rf it safely.
  const tempDir = await mkdtemp(join(tmpdir(), DEFAULT_SONAR_TEMPDIR_PREFIX));
  const filePath = join(tempDir, SONAR_PROPERTIES_FILENAME);
  await writeFile(filePath, content, 'utf-8');
  const cleanup = async (): Promise<void> => {
    try {
      await rm(tempDir, { recursive: true, force: true });
    } catch (err) {
      logger.warn(`[SonarQube] failed to remove sanitized properties temp dir ${tempDir}: ${String(err)}`);
    }
  };
  return { filePath, cleanup };
}
