import { CLI_NAME } from '@infra/brand';

export default `\
# ${CLI_NAME} — project configuration
# Generated by: ${CLI_NAME} init
#
# ecosystems: declarative list of ecosystems to scan and update.
#   Each entry configures the plugin, optional fixer strategy, validation commands, and advisors.
#   Plugin ids: composer, npm, pip
# protected_packages: packages that must NEVER be auto-upgraded beyond their stated constraint.
#   Any update requiring a constraint change needs explicit per-package authorization.
# safe_update_policy: patch/minor updates within existing constraints are auto-safe.

config_version: '1'

project:
  name: '{{projectName}}'
  client: '{{client}}'

# Declare ecosystems to scan and update.
# id must match a registered plugin (e.g. composer, npm, pip).
# fixer: strategy id for automated remediation ('osv' (default) | 'npm-audit').
# validationCommands: commands to run after updates to verify correctness.
# advisors: commands to run for security/health analysis.
ecosystems:
{{#each ecosystems}}
  - id: '{{id}}'{{#if hasFixer}}
    fixer: '{{fixer}}'{{/if}}
    validationCommands:{{#if hasValidationCommands}}
{{#each validationCommands}}      - name: '{{name}}'
        command: '{{command}}'
{{/each}}{{else}} []
{{/if}}{{#if hasAdvisors}}    advisors:
{{#each advisors}}      - name: '{{name}}'
        command: '{{command}}'
{{/each}}{{/if}}
{{/each}}
# Add packages that must not be auto-upgraded beyond their constraint.
protected_packages:
{{#each protectedPackageEcosystems}}
  {{#if active}}
  {{id}}:
    []
    # - package: '{{examplePackage}}'
    #   constraint: '{{exampleConstraint}}'
    #   reason: '{{exampleReason}}'
  {{else}}
  {{id}}: []
  {{/if}}
{{/each}}

safe_update_policy:
  allow_patch_and_minor_within_constraints: true
  require_authorization_for_constraint_change: true

conflict_resolution: 'stop_and_ask'

report_language: '{{reportLanguage}}'

{{#if hasOutputs}}
outputs:
  formats: [{{#each outputFormats}}'{{this}}'{{#unless @last}}, {{/unless}}{{/each}}]{{#if outputsDir}}
  dir: '{{outputsDir}}'{{/if}}
{{else}}
# outputs:                               # optional — output configuration
#   formats: ['markdown']
#   dir: '.${CLI_NAME}/reports'
{{/if}}

{{#if enableSonarQube}}
scanners:
  sonarqube:
    enabled: true
    # mode: 'managed' (default) — the CLI provisions an ephemeral SonarQube
    #       container via Docker, generates a token automatically, tears it
    #       down on exit. Requires Docker. No external SonarQube server needed.
    # mode: 'external' — sonar.host.url and sonar.projectKey come from
    #       sonar-project.properties at your project root; SONAR_TOKEN env var
    #       provides auth. Use this when you have an existing SonarQube server.
    mode: '{{sonarQubeMode}}'
    on_failure: 'warn'
    # ce_task_timeout_seconds: 120     # optional — seconds to wait for Compute Engine task before
    #                                  #   fetching quality gate; 0 disables waiting (default: 120)
    # scanner_timeout_seconds: 300     # optional — max seconds for sonar-scanner subprocess (default: 300)
    # dynamic_timeout: true            # optional — auto-scale timeouts by ncloc from last analysis
    #                                  #   true (default): fetch ncloc pre-scan, scale up for large projects
    #                                  #   false: use only static ce_task/scanner_timeout_seconds values
    # timeout_scale:                   # optional — multipliers for dynamic timeout (only when dynamic_timeout: true)
    #   scanner_seconds_per_kloc: 3    # seconds of scanner budget per 1,000 lines (default: 3)
    #   ce_seconds_per_kloc: 1.5       # seconds of CE budget per 1,000 lines (default: 1.5)
    # send_branch_name: false          # optional — forward git branch as -Dsonar.branch.name
    #                                  #   (requires SonarQube Developer Edition or higher)
    # scanner_image: 'sonarsource/sonar-scanner-cli:latest'  # optional — only used in managed mode
    #                                                        # when local sonar-scanner is unavailable
    # server_image: 'sonarqube:lts-community'  # managed mode only — SonarQube CE server image (NOT the sonar-scanner-cli image; use scanner_image for that)
    #
    # NOTE: project_key, host_url, sources, exclusions, etc. live in sonar-project.properties.
    #       Run "${CLI_NAME} init" (with SonarQube enabled) to generate a template if missing.

{{else}}
# scanners:                              # optional — additional scanner engines
#   sonarqube:
#     enabled: true
#     mode: 'managed'                    # 'managed' (default) | 'external'
#     on_failure: 'warn'                 # 'warn' (default) | 'fail'
#     # ce_task_timeout_seconds: 120     # optional — seconds to wait for CE task (0 = disable; default: 120)
#     # scanner_timeout_seconds: 300     # optional — max seconds for sonar-scanner subprocess (default: 300)
#     # dynamic_timeout: true            # optional — auto-scale timeouts by ncloc (default: true)
#     # timeout_scale:                   # optional — per-kloc multipliers (scanner_seconds_per_kloc: 3, ce_seconds_per_kloc: 1.5)
#     # send_branch_name: false          # optional — requires Developer Edition or higher
#     # scanner_image: 'sonarsource/sonar-scanner-cli:latest'  # optional — managed-mode container fallback
#     # project_key, host_url, exclusions, etc. live in sonar-project.properties.
#   osv:
#     runner: 'docker'                   # 'docker' (default) | 'local'
#                                        #   docker — always run via an ephemeral container (default)
#                                        #   local  — require a locally installed osv-scanner binary ⚠ warns
#     image: 'ghcr.io/google/osv-scanner:latest'  # optional — Docker image override
{{/if}}

# scan:                                   # optional — explicit scan path configuration
#   paths:
#     - app/                             # directory — scans recursively for lock files
#     - frontend/package-lock.json       # explicit file path
#   exclude:
#     - node_modules/
#   auto_discover: true                  # set to false to disable root-level scan

# workflow:                               # optional — git/PR automation for fix runs
#   create_branch: false                 # create a branch + commit before applying fixes
#   open_pr: false                       # push branch and open a GitHub PR (implies create_branch)
#                                        #   requires the gh CLI installed and authenticated
#   branch_prefix: 'fix/${CLI_NAME}-'   # prefix for the generated branch name
#   pr_title: 'fix: apply safe dependency updates'  # custom PR title

# cloud_storage:                         # optional — upload reports to cloud storage after generation
#   provider: google_drive
#   folder_id: 'YOUR_GOOGLE_DRIVE_FOLDER_ID'   # set automatically by '${CLI_NAME} cloud-setup'
#
# To connect Google Drive, run: ${CLI_NAME} cloud-setup
# Required environment variables (OAuth 2.0 Desktop app credentials from GCP Console):
#   DEEP_HEALTH_GOOGLE_CLIENT_ID=<your-oauth2-client-id>
#   DEEP_HEALTH_GOOGLE_CLIENT_SECRET=<your-oauth2-client-secret>
# Tokens are stored in: ~/.config/${CLI_NAME}/tokens.json (chmod 600)
`;
