/**
 * Template generator for sonar-project.properties.
 *
 * Called by `security-scan init` when the user enables SonarQube and the project
 * root does not already have a `sonar-project.properties` file. The generated
 * file contains project-level analysis configuration only — NO credentials,
 * NO host URL, NO token. Those are CLI-managed (managed mode) or env-var-based
 * (external mode).
 *
 * Common asset/binary exclusions (always applied, regardless of ecosystem):
 * - Images: png, jpg, jpeg, gif, svg, webp, ico, bmp, tiff
 * - Fonts: woff, woff2, ttf, eot, otf
 * - Media: mp4, webm, mp3, wav, mov, avi
 * - Other binaries: pdf, zip, gz, tar
 * - Source maps: map
 *
 * Ecosystem-aware defaults:
 * - npm      → excludes node_modules, tests, dist, build, coverage, .next, .nuxt,
 *              minified JS/CSS (recursive globs)
 * - composer → excludes vendor, tests, coverage, storage, bootstrap/cache,
 *              public/css, public/js, public/vendor, IDE helper stubs
 * - pip      → excludes venv, .venv, __pycache__, tests, coverage, htmlcov,
 *              .tox, egg-info (recursive globs)
 *
 * Sources default to './' — users typically refine this later; '.' is a safe
 * starting point that covers most layouts.
 */

import { writeFile, access } from 'node:fs/promises';
import { resolve } from 'node:path';

import { CLI_NAME } from '@infra/brand';
import { normalizeSonarProjectKey } from '@infra/config/generator';

const COMMON_SONAR_EXCLUSIONS: string[] = [
  // Images
  '**/*.png', '**/*.jpg', '**/*.jpeg', '**/*.gif', '**/*.svg', '**/*.webp',
  '**/*.ico', '**/*.bmp', '**/*.tiff',
  // Fonts
  '**/*.woff', '**/*.woff2', '**/*.ttf', '**/*.eot', '**/*.otf',
  // Media
  '**/*.mp4', '**/*.webm', '**/*.mp3', '**/*.wav', '**/*.mov', '**/*.avi',
  // Other binaries
  '**/*.pdf', '**/*.zip', '**/*.gz', '**/*.tar',
  // Source maps
  '**/*.map',
];

const ECOSYSTEM_SONAR_EXCLUSIONS: Record<string, string[]> = {
  npm: ['node_modules/**', 'tests/**', 'dist/**', 'build/**', 'coverage/**', '.next/**', '.nuxt/**', '**/*.min.js', '**/*.min.css'],
  composer: ['vendor/**', 'tests/**', 'coverage/**', 'storage/**', 'bootstrap/cache/**', 'public/css/**', 'public/js/**', 'public/vendor/**', '_ide_helper*.php'],
  pip: ['venv/**', '.venv/**', '**/__pycache__/**', 'tests/**', 'coverage/**', 'htmlcov/**', '.tox/**', '*.egg-info/**'],
};

const DEFAULT_EXCLUSIONS = ['tests/**'];

export interface SonarPropertiesTemplateInput {
  projectName: string;
  /** Ecosystem ids selected by the user (e.g. ['npm', 'composer']). */
  ecosystemIds: readonly string[];
}

/**
 * Produce the contents of a new sonar-project.properties file.
 *
 * The file is intentionally minimal — everything is inline-commented and
 * ready to edit. Users almost always want to customize `sonar.sources` and
 * `sonar.exclusions` to match their layout; the generated defaults are safe
 * starting points.
 */
export function buildSonarPropertiesTemplate(input: SonarPropertiesTemplateInput): string {
  const projectKey = normalizeSonarProjectKey(input.projectName);
  const projectName = input.projectName || 'My Project';

  // Union of ecosystem-specific exclusions, deduplicated, preserving order.
  const seen = new Set<string>();
  const exclusions: string[] = [];
  let ecosystemMatched = false;
  for (const id of input.ecosystemIds) {
    const ecosystemPatterns = ECOSYSTEM_SONAR_EXCLUSIONS[id];
    if (ecosystemPatterns !== undefined) {
      ecosystemMatched = true;
      for (const pattern of ecosystemPatterns) {
        if (!seen.has(pattern)) {
          seen.add(pattern);
          exclusions.push(pattern);
        }
      }
    }
  }
  if (!ecosystemMatched) {
    for (const pattern of DEFAULT_EXCLUSIONS) {
      if (!seen.has(pattern)) {
        seen.add(pattern);
        exclusions.push(pattern);
      }
    }
  }
  // Always append common asset/binary exclusions regardless of ecosystem.
  for (const pattern of COMMON_SONAR_EXCLUSIONS) {
    if (!seen.has(pattern)) {
      seen.add(pattern);
      exclusions.push(pattern);
    }
  }

  const lines: string[] = [
    '# sonar-project.properties',
    `# Generated by \`${CLI_NAME} init\`.`,
    '#',
    '# This file describes WHAT to analyze. CLI-managed concerns (server URL,',
    '# auth token, scan mode) live in security-scan.config.json under scanners.sonarqube.',
    '#',
    '# Do NOT add `sonar.login` or `sonar.password` here — sonar-scanner ≥5',
    '# rejects them. Use the SONAR_TOKEN environment variable instead (external',
    '# mode), or let the CLI manage it (managed mode).',
    '',
    `sonar.projectKey=${projectKey}`,
    `sonar.projectName=${projectName}`,
    'sonar.projectVersion=1.0.0',
    '',
    '# Root directory for analysis. Refine to point at your source folders.',
    'sonar.sources=./',
    'sonar.sourceEncoding=UTF-8',
    '',
    '# Paths excluded from analysis. Adjust to match your project layout.',
    `sonar.exclusions=${exclusions.join(',')}`,
    '',
    '# External mode only: uncomment and point at your SonarQube server.',
    "# Managed mode ignores this — the CLI overrides it with the ephemeral container's URL.",
    '# sonar.host.url=http://localhost:9000',
  ];
  return lines.join('\n') + '\n';
}

/**
 * Write the sonar-project.properties template at `<cwd>/sonar-project.properties`
 * if it doesn't already exist.
 *
 * Returns:
 * - 'created' when a new file was written
 * - 'skipped-existing' when a file already exists (we never overwrite; preserving
 *   user content is worth more than keeping the generator idempotent)
 */
export async function writeSonarPropertiesTemplateIfMissing(
  cwd: string,
  input: SonarPropertiesTemplateInput,
): Promise<'created' | 'skipped-existing'> {
  const filePath = resolve(cwd, 'sonar-project.properties');
  try {
    await access(filePath);
    return 'skipped-existing';
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
  }
  const content = buildSonarPropertiesTemplate(input);
  await writeFile(filePath, content, 'utf-8');
  return 'created';
}
