#!/usr/bin/env sh
# build-sea.sh — Build a Node.js SEA (Single Executable Application) binary.
#
# Usage:
#   CLI_NAME=security-scan TARGET_SUFFIX=linux-x64 ./scripts/build-sea.sh
#
# Environment variables:
#   CLI_NAME         — binary name (default: security-scan)
#   TARGET_SUFFIX    — platform suffix appended to binary (e.g. linux-x64, win-x64)
#   VERSION          — optional version string (e.g. 1.2.0 or v1.2.0); when set,
#                      included in the output filename between CLI_NAME and TARGET_SUFFIX
#   BUILD_TIMESTAMP  — optional build timestamp (e.g. 20260518-120000); when set
#                      alongside VERSION, appended after VERSION in the filename
#
# Output filename format:
#   With VERSION + BUILD_TIMESTAMP : {CLI_NAME}-{VERSION}-{BUILD_TIMESTAMP}-{TARGET_SUFFIX}{EXT}
#   With VERSION only              : {CLI_NAME}-{VERSION}-{TARGET_SUFFIX}{EXT}
#   Without either                 : {CLI_NAME}-{TARGET_SUFFIX}{EXT}
#
# Prerequisites:
#   - Node.js 26+
#   - dist-sea/security-scan.cjs  (built via: npm run build:sea-bundle)
#   - npx postject (installed via postject in devDependencies or npx on demand)
#
# The postject fuse sentinel NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
# must not be changed — it is the exact string Node.js looks for in the binary.

set -e

CLI_NAME="${CLI_NAME:-security-scan}"
TARGET_SUFFIX="${TARGET_SUFFIX:-linux-x64}"
VERSION="${VERSION:-}"
BUILD_TIMESTAMP="${BUILD_TIMESTAMP:-}"

BLOB="dist-sea/sea-prep.blob"
DIST_DIR="dist-bin"

if [ -n "${VERSION}" ]; then
  PACKAGE_VERSION="$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' package.json | head -n 1)"
  RELEASE_VERSION="${VERSION#v}"

  if [ -z "${PACKAGE_VERSION}" ]; then
    echo "Error: package.json version could not be read." >&2
    exit 1
  fi

  if [ "${RELEASE_VERSION}" != "${PACKAGE_VERSION}" ]; then
    echo "Error: Release version ${RELEASE_VERSION} does not match package.json version ${PACKAGE_VERSION}." >&2
    exit 1
  fi
fi

# On Windows (MSYS/Git Bash/Cygwin), append .exe
case "$TARGET_SUFFIX" in
  win-*) EXT=".exe" ;;
  *)     EXT="" ;;
esac

# Build the optional version/timestamp infix: -VERSION-TIMESTAMP, -VERSION, or empty
if [ -n "${VERSION}" ] && [ -n "${BUILD_TIMESTAMP}" ]; then
  VERSION_TAG="-${VERSION}-${BUILD_TIMESTAMP}"
elif [ -n "${VERSION}" ]; then
  VERSION_TAG="-${VERSION}"
else
  VERSION_TAG=""
fi

OUT_BIN="${DIST_DIR}/${CLI_NAME}${VERSION_TAG}-${TARGET_SUFFIX}${EXT}"

# ------------------------------------------------------------------
# 1. Verify the SEA blob exists (generated by: npm run build:sea)
# ------------------------------------------------------------------
if [ ! -f "${BLOB}" ]; then
  echo "Error: SEA blob not found at ${BLOB}." >&2
  echo "Run 'npm run build:sea' to generate it before calling this script." >&2
  exit 1
fi

# ------------------------------------------------------------------
# 2. Create dist-bin/ and copy the node binary
# ------------------------------------------------------------------
mkdir -p "${DIST_DIR}"

NODE_BIN="$(command -v node)"
echo "Copying node binary from ${NODE_BIN} to ${OUT_BIN} ..."
cp "${NODE_BIN}" "${OUT_BIN}"

# ------------------------------------------------------------------
# 3. macOS: strip existing code signature before injection
# ------------------------------------------------------------------
OS="$(uname -s 2>/dev/null || echo Unknown)"
if [ "$OS" = "Darwin" ]; then
  echo "macOS detected — removing existing code signature ..."
  codesign --remove-signature "${OUT_BIN}"
fi

# ------------------------------------------------------------------
# 4. Inject the SEA blob using postject
# ------------------------------------------------------------------
echo "Injecting SEA blob into ${OUT_BIN} ..."

if [ "$OS" = "Darwin" ]; then
  npx postject "${OUT_BIN}" NODE_SEA_BLOB "${BLOB}" \
    --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 \
    --macho-segment-name NODE_SEA
else
  npx postject "${OUT_BIN}" NODE_SEA_BLOB "${BLOB}" \
    --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
fi

# ------------------------------------------------------------------
# 5. macOS: re-sign the binary after injection
# ------------------------------------------------------------------
if [ "$OS" = "Darwin" ]; then
  echo "Re-signing binary with ad-hoc signature ..."
  codesign --sign - "${OUT_BIN}"
fi

# ------------------------------------------------------------------
# 6. Linux: rename real binary to .bin and create a wrapper script
#    that uses ldd to detect missing shared libraries before exec-ing
#    the real binary.
# ------------------------------------------------------------------
case "$TARGET_SUFFIX" in
  linux-*)
    REAL_BIN="${OUT_BIN}.bin"
    echo "Linux target — renaming ${OUT_BIN} to ${REAL_BIN} ..."
    mv "${OUT_BIN}" "${REAL_BIN}"
    chmod +x "${REAL_BIN}"

    echo "Creating ldd-based dependency wrapper script at ${OUT_BIN} ..."
    cat > "${OUT_BIN}" <<'WRAPPER_EOF'
#!/usr/bin/env sh
# Wrapper for NODE_SEA_CLI_NAME — uses ldd to detect missing shared libs before exec.
# Generated by build-sea.sh; do not edit by hand.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REAL_BIN="${SCRIPT_DIR}/NODE_SEA_CLI_NAME_BINARY"

# Use ldd to detect missing shared libraries if available.
# On minimal systems where ldd is absent, skip the check and exec directly
# (let the OS error surface naturally).
if command -v ldd >/dev/null 2>&1; then
  MISSING_LIBS="$(ldd "${REAL_BIN}" 2>/dev/null | grep 'not found')"
  if [ -n "${MISSING_LIBS}" ]; then
    echo "Error: NODE_SEA_CLI_NAME cannot start — missing shared libraries:" >&2
    echo "" >&2
    echo "${MISSING_LIBS}" | while IFS= read -r line; do
      echo "  ${line}" >&2
    done
    echo "" >&2
    echo "Install the missing libraries using your distro's package manager." >&2
    echo "" >&2
    echo "  On Debian / Ubuntu:" >&2
    echo "    Missing libraries are often in packages like libatomic1, libstdc++6, etc." >&2
    echo "    Use: apt-cache search <libname>  to find the right package." >&2
    echo "    Then: sudo apt-get install -y <package-name>" >&2
    echo "" >&2
    echo "  On Fedora / RHEL / CentOS:" >&2
    echo "    Missing libraries are often in packages like libatomic, libstdc++, etc." >&2
    echo "    Use: dnf provides <libname>  to find the right package." >&2
    echo "    Then: sudo dnf install -y <package-name>" >&2
    echo "" >&2
    exit 1
  fi
fi

exec "${REAL_BIN}" "$@"
WRAPPER_EOF

    # Replace placeholders with the actual binary name
    # Use a temp file to avoid sed -i portability issues across Linux/macOS
    WRAPPER_TMP="${OUT_BIN}.tmp"
    BINARY_BASENAME="$(basename "${REAL_BIN}")"
    CLI_NAME_DISPLAY="${CLI_NAME}"
    sed "s/NODE_SEA_CLI_NAME_BINARY/${BINARY_BASENAME}/g; s/NODE_SEA_CLI_NAME/${CLI_NAME_DISPLAY}/g" \
      "${OUT_BIN}" > "${WRAPPER_TMP}"
    mv "${WRAPPER_TMP}" "${OUT_BIN}"
    chmod +x "${OUT_BIN}"

    echo "Done: wrapper=${OUT_BIN}  real binary=${REAL_BIN}"
    ;;
  *)
    echo "Done: ${OUT_BIN}"
    ;;
esac
